services:
  - type: web
    name: yolo-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT --timeout 120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    plan: free
    healthCheckPath: /health
    autoDeploy: true